# Generated by Django 2.0.3 on 2018-09-29 02:54

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='title', unique=True, verbose_name='Identificador')),
                ('text', models.TextField(verbose_name='Texto')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
                ('photo', models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-date'],
            },
        ),
    ]
