# Generated by Django 2.0.3 on 2018-03-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='legenda teste', max_length=100, verbose_name='Legenda'),
            preserve_default=False,
        ),
    ]
