# Generated by Django 2.0.3 on 2018-05-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
