# Generated by Django 2.0.3 on 2018-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_auto_20181021_0205'),
        ('team', '0003_remove_team_state'),
        ('news', '0002_auto_20181021_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='news',
            name='tagChampionship',
            field=models.ManyToManyField(to='championship.Championship'),
        ),
        migrations.AddField(
            model_name='news',
            name='tagTeam',
            field=models.ManyToManyField(to='team.Team'),
        ),
    ]
