# Generated by Django 2.0.3 on 2018-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180405_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
