# Generated by Django 2.0.3 on 2018-10-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181027_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tagChampionship',
            field=models.ManyToManyField(blank=True, to='championship.Championship', verbose_name='Tag de campeonato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tagTeam',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='Tag de time'),
        ),
    ]
