# Generated by Django 2.0.3 on 2018-10-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181027_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
