# Generated by Django 2.0.3 on 2018-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tagTeam',
            new_name='teamTag',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tagChampionship',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='news.Tag', verbose_name='Tag'),
        ),
    ]
