# Generated by Django 2.0.3 on 2018-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='País'),
        ),
    ]
