# Generated by Django 2.0.3 on 2018-10-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_nationality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'uf')},
        ),
    ]
