# Generated by Django 2.0.3 on 2018-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181020_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='players/photo/', verbose_name='Foto')),
                ('link', models.URLField(max_length=5000, verbose_name='Link')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
