# Generated by Django 2.0.3 on 2018-05-15 00:34

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('shortName', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Região')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária')),
                ('secundaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(unique=True, verbose_name='Ano')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='league', unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.League', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Edição de campeonato',
                'verbose_name_plural': 'Edições de campeonatos',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='Identificador')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photo/', verbose_name='Foto')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número da camisa')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('hometown', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade natal')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('experience', models.DateField(blank=True, null=True, verbose_name='Experiência')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('initials', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('shortName', models.CharField(max_length=255, verbose_name='Nome abreviado')),
                ('initials', models.CharField(max_length=3, verbose_name='Sigla')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='Identificador')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('foundation', models.DateField(blank=True, null=True, verbose_name='Data de fundação')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('primaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária')),
                ('secundaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária')),
                ('terciaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor terciária')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Position', verbose_name='Posição'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Time'),
        ),
    ]
