# Generated by Django 2.0.3 on 2018-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='terciaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor terciária'),
        ),
    ]
