# Generated by Django 2.0.3 on 2018-04-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='leagueedition',
            options={'ordering': ['year'], 'verbose_name': 'Edição de campeonato', 'verbose_name_plural': 'Edições de campeonatos'},
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.DateField(blank=True, null=True, verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='player',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade natal'),
        ),
        migrations.AlterField(
            model_name='player',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da camisa'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photo/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Position', verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Time'),
        ),
    ]
