# Generated by Django 2.0.3 on 2018-10-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
    ]
