# Generated by Django 2.0.3 on 2018-04-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180420_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='primaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária'),
        ),
        migrations.AddField(
            model_name='league',
            name='secundaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária'),
        ),
        migrations.AlterField(
            model_name='league',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='foundation',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fundação'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='primaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária'),
        ),
        migrations.AlterField(
            model_name='team',
            name='secundaryColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária'),
        ),
    ]
