# Generated by Django 2.0.8 on 2019-05-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190505_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Jogador', 'verbose_name_plural': '2. Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Posição', 'verbose_name_plural': '3. Posições'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Time', 'verbose_name_plural': '1. Times'},
        ),
        migrations.AlterModelOptions(
            name='teamcategory',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Divisão do time', 'verbose_name_plural': '0. Divisões dos times'},
        ),
    ]
