# Generated by Django 2.0.3 on 2018-10-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_player_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='state',
        ),
    ]
