# Generated by Django 2.0.3 on 2018-07-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180722_1745'),
        ('team', '0002_league_terciarycolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueedition',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometown',
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nationality', verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='player',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='player',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='LeagueEdition',
        ),
    ]
