# Generated by Django 2.0.3 on 2018-07-12 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20180531_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.LeagueEdition', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Conferência',
                'verbose_name_plural': 'Conferências',
                'ordering': ['league', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreA', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time A')),
                ('scoreB', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time B')),
                ('week', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora')),
                ('place', models.CharField(blank=True, max_length=900, null=True, verbose_name='Local')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Conference', verbose_name='Conferência')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='team.Team', verbose_name='Time A')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='team.Team', verbose_name='Time B')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['conference', 'week', 'date'],
            },
        ),
    ]
