# Generated by Django 2.0.8 on 2019-10-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_subteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subteam',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Especialidade', 'verbose_name_plural': '4. Especialidades'},
        ),
    ]
