# Generated by Django 2.0.3 on 2018-04-20 19:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='recife-mariners', editable=False, max_length=255, populate_from='name', unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
