# Generated by Django 2.0.3 on 2018-04-20 19:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20180420_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueedition',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='league', unique=True, verbose_name='Identificador'),
        ),
    ]
