# Generated by Django 2.0.3 on 2018-07-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20180722_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueedition',
            name='league',
        ),
        migrations.AlterField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.League', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='league',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2018, null=True, verbose_name='Ano'),
        ),
        migrations.DeleteModel(
            name='LeagueEdition',
        ),
    ]
