# Generated by Django 2.0.3 on 2018-07-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180722_1745'),
        ('team', '0007_auto_20180722_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hometown',
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nationality', verbose_name='Nacionalidade'),
        ),
    ]
