# Generated by Django 2.0.3 on 2018-07-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20180722_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='league',
        ),
        migrations.RemoveField(
            model_name='game',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='game',
            name='teamA',
        ),
        migrations.RemoveField(
            model_name='game',
            name='teamB',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
