# Generated by Django 2.0.3 on 2018-05-08 00:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_terciarycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=0, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
