# Generated by Django 2.0.3 on 2018-07-22 22:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0009_auto_20180722_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('shortName', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária')),
                ('secundaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária')),
                ('terciaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor terciária')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Conferência')),
                ('weeks', models.IntegerField(blank=True, null=True, verbose_name='Semanas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Championship', verbose_name='Campeonato')),
                ('teams', models.ManyToManyField(to='team.Team')),
            ],
            options={
                'verbose_name': 'Conferência',
                'verbose_name_plural': 'Conferências',
                'ordering': ['championship', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Divisão')),
                ('playoffs', models.IntegerField(blank=True, null=True, verbose_name='Classificados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Conference', verbose_name='Conferência')),
                ('teams', models.ManyToManyField(to='team.Team')),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'ordering': ['conference', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora')),
                ('place', models.CharField(blank=True, max_length=900, null=True, verbose_name='Local')),
                ('scoreA', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time A')),
                ('scoreB', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time B')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='teamA-teamB-date', unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Conference', verbose_name='Conferência')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='team.Team', verbose_name='Time A')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='team.Team', verbose_name='Time B')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['conference', 'week', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2018, null=True, verbose_name='Ano')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Championship', verbose_name='Campeonato')),
                ('teams', models.ManyToManyField(to='team.Team')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['championship'],
            },
        ),
    ]
