# Generated by Django 2.0.8 on 2019-03-25 02:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('team', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('shortName', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor primária')),
                ('secundaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor secundária')),
                ('terciaryColor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor terciária')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': '1. Campeonatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Conferência')),
                ('weeks', models.IntegerField(blank=True, null=True, verbose_name='Semanas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Conferência',
                'verbose_name_plural': '3. Conferências',
                'ordering': ['season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Divisão')),
                ('playoffs', models.IntegerField(blank=True, null=True, verbose_name='Classificados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Conference', verbose_name='Conferência')),
                ('teams', models.ManyToManyField(blank=True, to='team.Team', verbose_name='Times')),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': '4. Divisões',
                'ordering': ['conference', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora')),
                ('ended', models.BooleanField(verbose_name='Finalizado')),
                ('scoreA', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time A')),
                ('scoreB', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time B')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Local')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='team.Team', verbose_name='Time A')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='team.Team', verbose_name='Time B')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': '7. Jogos',
                'ordering': ['week', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255, verbose_name='Semana')),
                ('week', models.CharField(blank=True, max_length=255, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': '6. Rodadas',
                'ordering': ['season', 'phase', 'week'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2019, null=True, verbose_name='Ano')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=django.utils.text.slugify, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Campeão')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Championship', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': '2. Temporadas',
                'ordering': ['championship', '-year'],
            },
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Season', verbose_name='Temporada'),
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Round', verbose_name='Rodada'),
        ),
        migrations.AddField(
            model_name='conference',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Season', verbose_name='Temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('phase', 'season')},
        ),
    ]
