# Generated by Django 2.0.8 on 2019-03-25 03:21

import autoslug.fields
from django.db import migrations
import django.utils.text


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=0, editable=False, max_length=255, populate_from=django.utils.text.slugify, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
