# Generated by Django 2.0.3 on 2018-07-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
