# Generated by Django 2.0.8 on 2019-03-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_round_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='week',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
