# Generated by Django 2.0.8 on 2019-04-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_auto_20190325_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Tipo de campeonato',
                'verbose_name_plural': '0. Tipos de campeonatos',
            },
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['season', '-week', 'phase'], 'verbose_name': 'Rodada', 'verbose_name_plural': '6. Rodadas'},
        ),
        migrations.AddField(
            model_name='championship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='championship.ChampionshipCategory', verbose_name='Categoria'),
        ),
    ]
