# Generated by Django 2.0.8 on 2019-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_auto_20190420_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championshipcategory',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Tipo de campeonato', 'verbose_name_plural': '0. Tipos de campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year', 'championship'], 'verbose_name': 'Temporada', 'verbose_name_plural': '2. Temporadas'},
        ),
        migrations.AddField(
            model_name='round',
            name='playoffs',
            field=models.BooleanField(default=False),
        ),
    ]
