# Generated by Django 2.0.3 on 2018-11-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_state'),
        ('championship', '0004_auto_20181102_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora')),
                ('place', models.CharField(blank=True, max_length=900, null=True, verbose_name='Local')),
                ('scoreA', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time A')),
                ('scoreB', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do time B')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='team.Team', verbose_name='Time A')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='team.Team', verbose_name='Time B')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-week', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=255, verbose_name='Semana')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
                'ordering': ['-season', '-week'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Round', verbose_name='Rodada'),
        ),
    ]
