# Generated by Django 2.0.3 on 2018-11-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_auto_20181102_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('week', 'season')},
        ),
    ]
