# Generated by Django 2.0.8 on 2019-05-13 05:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_auto_20190512_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['week'], 'verbose_name': 'Jogo', 'verbose_name_plural': '7. Jogos'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='place',
        ),
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='phase', verbose_name='Identificador'),
        ),
    ]
