# Generated by Django 2.0.3 on 2018-11-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_auto_20181102_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='week',
        ),
    ]
