# Generated by Django 2.0.8 on 2020-01-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0007_auto_20200128_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='division',
            name='playoffs',
        ),
    ]
