# Generated by Django 2.0.3 on 2018-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_state'),
        ('championship', '0010_auto_20181111_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='teams',
            field=models.ManyToManyField(blank=True, through='championship.Campaign', to='team.Team', verbose_name='Times'),
        ),
    ]
