# Generated by Django 2.0.3 on 2018-11-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0011_division_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='defeties',
            new_name='defeats',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='dfsPoints',
            new_name='dfPoints',
        ),
    ]
