# Generated by Django 2.0.3 on 2018-11-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0012_auto_20181111_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['division', '-victories', '-draws', 'defeats'], 'verbose_name': 'Campanha', 'verbose_name_plural': 'Campanhas'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-season', '-phase'], 'verbose_name': 'Rodada', 'verbose_name_plural': 'Rodadas'},
        ),
        migrations.RenameField(
            model_name='round',
            old_name='week',
            new_name='phase',
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('phase', 'season')},
        ),
    ]
