# Generated by Django 2.0.3 on 2018-11-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0013_auto_20181118_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-season', '-phase', '-week'], 'verbose_name': 'Rodada', 'verbose_name_plural': 'Rodadas'},
        ),
        migrations.AddField(
            model_name='round',
            name='week',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='round',
            name='phase',
            field=models.CharField(max_length=255, verbose_name='Fase'),
        ),
    ]
