# Generated by Django 2.0.3 on 2018-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0014_auto_20181118_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='phase',
            field=models.CharField(max_length=255, verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='round',
            name='week',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data'),
        ),
    ]
