# Generated by Django 2.0.8 on 2019-10-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20191012_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='playerB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerB', to='team.Player', verbose_name='Jogador B'),
        ),
    ]
